version: "3.11"

services:
  fastapi:
    build: .
    container_name: fast
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    env_file:
      - ./.env
    ports:
      - '8000:8000'
    depends_on:
      - celery_worker_chart
      - celery_beat_chart
      - redis_chart

  celery_worker_chart:
    build: .
    container_name: celery_worker
    command: celery -A tasks worker --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - redis_chart

  celery_beat_chart:
    build: .
    container_name: celery_beat
    command: celery -A tasks beat --loglevel=INFO
    volumes:
      - .:/app
    depends_on:
      - redis_chart

  redis_chart:
    image: redis:6-alpine
    container_name: redis_chart
